# Generated by Django 6.1 on 2026-08-16 12:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='glb_file',
            field=models.FileField(blank=True, help_text='Optional. If set, an interactive 3D viewer is shown on the project page.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='models/'),
        ),
    ]
