# Generated by Django 6.1 on 2026-08-16 14:49

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_glb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='glb_file',
            field=models.FileField(blank=True, help_text='Optional. If set, an interactive 3D viewer is shown on the project page.', null=True, storage=config.storages.R2Storage(), upload_to='models/'),
        ),
    ]
